name: Add a release draft

on:
  push:
    branches:
      - main

jobs:
  update_release_draft:
    name: Add or update release draft
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: toolmantim/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
